# Use a imagem oficial do n8n
FROM docker.n8n.io/n8nio/n8n

# Defina variáveis de ambiente para o banco de dados PostgreSQL
ENV DB_TYPE=postgresdb \
    DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE} \
    DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST} \
    DB_POSTGRESDB_PORT=${DB_POSTGRESDB_PORT} \
    DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER} \
    DB_POSTGRESDB_SCHEMA=${DB_POSTGRESDB_SCHEMA} \
    DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD} \
    DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED=${DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED} \
    DB_POSTGRESDB_SSL_ENABLED=${DB_POSTGRESDB_SSL_ENABLED} \
    WEBHOOK_URL=${WEBHOOK_URL} \
    WEBHOOK_TUNNEL_URL=${WEBHOOK_TUNNEL_URL} \
    VUE_APP_URL_BASE_API=${VUE_APP_URL_BASE_API} \
    N8N_HOST=${N8N_HOST} \
    POSTGRES_NON_ROOT_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD} \
    POSTGRES_NON_ROOT_USER=${POSTGRES_NON_ROOT_USER}


# Expor a porta para que o n8n possa ser acessado
EXPOSE 5678

# Crie um volume para armazenar os dados persistentes do n8n
VOLUME ["/home/node/.n8n"]
