services:
  - name: n8n
    type: web
    env: docker
    image: 
      url: docker.n8n.io/n8nio/n8n
    region: oregon
    plan: free  
    dockerCommand: "n8n start"  # Comando de inicialização, ajuste conforme necessário
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: postgres
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        fromSecret: POSTGRES_DB
      - key: DB_POSTGRESDB_USER
        fromSecret: POSTGRES_NON_ROOT_USER
      - key: DB_POSTGRESDB_PASSWORD
        fromSecret: POSTGRES_NON_ROOT_PASSWORD
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: n8n_storage
      mountPath: /home/node/.n8n
      sizeGB: 1

  - name: postgres
    type: web
    env: docker
    region: oregon
    plan: free 
    image: 
      url: docker.io/postgres:16
    envVars:
      - key: POSTGRES_USER
        fromSecret: POSTGRES_USER
      - key: POSTGRES_PASSWORD
        fromSecret: POSTGRES_PASSWORD
      - key: POSTGRES_DB
        fromSecret: POSTGRES_DB
      - key: POSTGRES_NON_ROOT_USER
        fromSecret: POSTGRES_NON_ROOT_USER
      - key: POSTGRES_NON_ROOT_PASSWORD
        fromSecret: POSTGRES_NON_ROOT_PASSWORD
    autoDeploy: true
    disk:
      name: db_storage
      mountPath: /var/lib/postgresql/data
      sizeGB: 1 

